# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S0a1ZTzBAbVixtVEzxfU981SSvGDczXj
"""

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        less_than_pivot = [x for x in arr[1:] if x <= pivot]
        greater_than_pivot = [x for x in arr[1:] if x > pivot]
        print("Pivot:", pivot)
        print("Less than pivot:", less_than_pivot)
        print("Greater than pivot:", greater_than_pivot)
        print("--------------------")
        return quick_sort(less_than_pivot) + [pivot] + quick_sort(greater_than_pivot)

# Demo
arr = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("Original array:", arr)
print("--------------------")
sorted_arr = quick_sort(arr)
print("Sorted array:", sorted_arr)